apiVersion: v1
kind: Service
metadata:
  name: {{ include "my3tierapp.fullname" . }}-postgres-service
  labels:
  {{- include "my3tierapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresService.type }}
  selector:
    service: postgres
  {{- include "my3tierapp.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.postgresService.ports | toYaml | nindent 2 -}}