apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my3tierapp.fullname" . }}-frontend-ingress
  labels:
  {{- include "my3tierapp.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: k8sapp.info
    http:
      paths:
      - backend:
          service:
            name: '{{ include "my3tierapp.fullname" . }}-api-svc'
            port:
              number: 8090
        path: /api(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "my3tierapp.fullname" . }}-web-svc'
            port:
              number: 8080
        path: /web
        pathType: Prefix